version: "2"

services:
  # The web container is an instance of exactly the same Docker image as your
  # Cloud application container.
  web:
    build: "."
    links:
      - "db"
    # Change the port if you'd like to expose your project locally on a
    # different port, for example if you already use port 8000 for
    # something else.
    ports:
      - "8000"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"

    # The default command that the container starts with. If you'd like to run
    # the project locally in Live configuration, you will need to change this.
    # See https://docs.divio.com/en/latest/how-to/local-in-live-configuration/
    command: python manage.py runserver 0.0.0.0:8000
    # Add any environment variables your project needs to the .env-local file.
    # See https://docs.divio.com/en/latest/reference/configuration-environment-variables.html.

  # On the Cloud, your database runs on a dedicated cluster. Locally, we
  # replicate it in a Docker container called "db".
  db:
    image: postgres:15
    ports:
    - "5432:5435"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"
    volumes:
      - ".:/app:rw"
