version: '3'

services:

  db:
    restart: always
    image: postgres:15
    ports:
      - "5435:5435"
    environment:
      POSTGRES_DB: video_management
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust


  web:
    build: .
    command: bash -c python manage.py makemigrations && python manage.py migrate && python manage.py create-haziq-admin

    container_name: haziq-assignment
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
