# Generated by Django 4.2.6 on 2023-10-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.FloatField(choices=[(0.0, 'ZERO'), (0.5, 'HALF'), (1.0, 'ONE'), (1.5, 'ONE_AND_A_HALF'), (2.0, 'TWO'), (2.5, 'TWO_AND_A_HALF'), (3.0, 'THREE'), (3.5, 'THREE_AND_A_HALF'), (4.0, 'FOUR'), (4.5, 'FOUR_AND_A_HALF'), (5.0, 'FIVE')], default=0.0),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
