# Generated by Django 4.2.6 on 2023-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_ratings_user_alter_ratings_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='videos.tag'),
        ),
    ]
